### PR TITLE
Ios android both work

### PR DESCRIPTION
**Pull request by michaelbyrd123**

### CODE REVIEW

**Comment by jdegger** [comment]
Hi @michaelbyrd123, I do not completely understand the goal of your PR and what you were trying to achieve. Can we help you?

**Comment by michaelbyrd123** [comment]
@jdegger I was getting errors regarding unimplemented methods on the android side when i tried to run as is regarding the onAllQueuedButtonEventsProcessed.  I also had some issues using versions greater than 0.3.0 on ios, was getting module include errors with the flic2lib

**Comment by michaelbyrd123** [comment]
didnt meant the create a pull request, that was a fat finger.

**Comment by michaelbyrd123** [comment]
The main thing was the changes to this file to get rid of the errors I was seeing.  https://github.com/michaelbyrd123/react-native-flic2/blob/ios-android-both-work/android/src/main/java/nl/xguard/flic2/callback/flic2ButtonCallback.java

**Comment by jdegger** [comment]
The library has been updated since your PR. The errors might be gone in a rather large overhaul of the lib.

**Pull request closed without merging**
